## Spring actuator config
spring:
  application:
    name: transfer
  profiles:
    active: prod
  endpoints:
    actuator:
      enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: refresh
  config:
    import: "optional:configserver:"
    use-legacy-processing: true

