server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: ${KEY-STORE-PASSWORD}
    key-password: ${KEY-PASSWORD}
    key-store-type: PKCS12
    key-alias: springkey
    security:

spring:
  profiles: prod
