server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: ${KEYSTOREPASSWORD}
    key-password: ${KEYPASSWORD}
    key-store-type: PKCS12
    key-alias: springkey

spring:
  profiles: prod
